Use standardpath utils to locate opencc profiles
fcitx/fcitx5-chinese-addons pull request #119
Opened 2023-02-04 04:31 UTC by WhiredPlanck

This is useful for Android platform since it doesn't support any "standard" path on Linux.

2023-02-04 05:42 UTC, WhiredPlanck commented
LGTM on PC (AMD64)

![图片](https://user-images.githubusercontent.com/47623588/216751019-24a3cf2c-f4b2-4411-9079-e9224340212d.png)

2023-02-05 07:47 UTC, WhiredPlanck commented
LGTM on Android (Emulator, x86_64)

<img src="https://user-images.githubusercontent.com/47623588/216807579-91374e8c-a9e8-4b00-aada-5fe27cd168f0.png" width="240px" />

<img src="https://user-images.githubusercontent.com/47623588/216807660-0b5f3d67-7b3f-4f07-8035-7c89d1d005f7.png" width="240px" />

2023-02-05 17:18 UTC, wengxt requested changes

2023-02-05 17:18 UTC, wengxt commented on modules/chttrans/chttrans-opencc.cpp
> +    using namespace fcitx;
move this line to top of the file.

2023-02-05 17:18 UTC, wengxt commented on modules/chttrans/chttrans-opencc.cpp
> +    auto s2tProfile = config.openCCS2TProfile->empty()
create a common function for this part to avoid code duplication.

2023-02-06 12:58 UTC, WhiredPlanck commented
The test results above are still valid.

2023-02-07 17:36 UTC, merged